// Save-schema regression: resources and hotbar state must survive save/load.
// This is a light static guard because main.js is browser/DOM-bound.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const src = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const progressSrc = await readFile(new URL('../src/engine/progress.js', import.meta.url), 'utf8');

assert.match(src, /function snapshotInventory\(\)/, 'save code defines an inventory snapshot helper');
assert.match(src, /function restoreInventory\(src\)/, 'load code defines an inventory restore helper');
assert.match(src, /function snapshotHotbar\(\)/, 'save code defines a hotbar snapshot helper');
assert.match(src, /function restoreHotbar\(src\)/, 'load code defines a hotbar restore helper');
assert.match(src, /function snapshotEquipment\(\)/, 'save code defines an equipment snapshot helper');
assert.match(src, /function restoreEquipment\(src\)/, 'load code defines an equipment restore helper');
assert.match(src, /background:\s*timedSavePart\('background',[^\n]*BACKGROUND && BACKGROUND\.snapshot/, 'save payload includes day-night background state');
assert.match(src, /gases:\s*timedSavePart\('gases',[^\n]*GASES && GASES\.snapshot/, 'save payload includes active gas state');
assert.match(src, /wind:\s*timedSavePart\('wind',[^\n]*WIND && WIND\.snapshot/, 'save payload includes weather wind state');
assert.match(src, /seasons:\s*timedSavePart\('seasons',[^\n]*SEASONS && SEASONS\.snapshot/, 'save payload includes season clock state');
assert.match(src, /clouds:\s*timedSavePart\('clouds',[^\n]*CLOUDS && CLOUDS\.snapshot/, 'save payload includes cloud and storm weather state');
assert.match(src, /dynamo:\s*timedSavePart\('dynamo',[^\n]*DYNAMO && DYNAMO\.snapshot/, 'save payload includes dynamo machine state');
assert.match(src, /solar:\s*timedSavePart\('solar',[^\n]*SOLAR && SOLAR\.snapshot/, 'save payload includes solar panel battery state');
assert.match(src, /teleporters:\s*timedSavePart\('teleporters',[^\n]*TELEPORTERS && TELEPORTERS\.snapshot/, 'save payload includes teleporter machine state');
assert.match(src, /volcano:\s*timedSavePart\('volcano',[^\n]*VOLCANO && VOLCANO\.snapshot/, 'save payload includes volcano story-item and hazard state');
assert.match(src, /mobs:\s*timedSavePart\('mobs',[^\n]*MOBS && MOBS\.serialize/, 'save payload includes live mob ecology state');
assert.match(src, /ufo:\s*timedSavePart\('ufo',[^\n]*UFO && UFO\.snapshot/, 'save payload includes UFO visitor schedule state');
assert.match(src, /progress:\s*timedSavePart\('progress',[^\n]*PROGRESS && PROGRESS\.snapshot/, 'save payload includes trained progression state');
assert.match(src, /plants:\s*timedSavePart\('plants',[^\n]*PLANTS && PLANTS\.snapshot/, 'save payload includes living plant state');
assert.match(src, /inv:\s*timedSavePart\('inventory',[^\n]*snapshotInventory\(\)/, 'save payload includes resource inventory');
assert.match(src, /hotbar:\s*timedSavePart\('hotbar',[^\n]*snapshotHotbar\(\)/, 'save payload includes hotbar state');
assert.match(src, /equipment:\s*timedSavePart\('equipment',[^\n]*snapshotEquipment\(\)/, 'save payload includes equipped gear and outfit');
assert.match(src, /tool:\s*player\.tool/, 'save payload includes the active pickaxe');
assert.match(src, /energy:\+\(player\.energy\|\|0\)\.toFixed\(2\)/, 'save payload includes stored hero energy');
assert.match(src, /restoreInventory\(data\.inv\)/, 'load path restores resource inventory');
assert.match(src, /restoreHotbar\(data\.hotbar/, 'load path restores hotbar state');
assert.match(src, /restoreEquipment\(data\.equipment\)/, 'load path restores equipped gear and outfit');
assert.match(src, /BACKGROUND\.restore\(data\.background\)/, 'load path restores day-night background state');
assert.match(src, /GASES\.restore\(data\.gases,getTile,setTile\)/, 'load path restores active gas state through transient world writes');
assert.match(src, /GASES\.auditChunks\(restoredChunks,getTile\)/, 'load path re-audits saved gas tiles from chunks');
assert.match(src, /WIND\.restore\(data\.wind\)/, 'load path restores weather wind state');
assert.match(src, /SEASONS\.restore\(data\.seasons\)/, 'load path restores season clock state');
assert.match(src, /CLOUDS\.restore\(data\.clouds\)/, 'load path restores cloud and storm weather state');
assert.match(src, /DYNAMO\.restore\(data\.dynamo,getTile\)/, 'load path restores dynamo machine state after terrain');
assert.match(src, /SOLAR\.restore\(data\.solar,getTile\)/, 'load path restores solar panel battery state after terrain');
assert.match(src, /TELEPORTERS\.restore\(data\.teleporters,getTile\)/, 'load path restores teleporter batteries after terrain');
assert.match(src, /VOLCANO\.restore\(data\.volcano,getTile\)/, 'load path restores volcano story-item timers after terrain');
assert.match(src, /MOBS\.deserialize\(data\.mobs\)/, 'load path restores live mob ecology after terrain');
assert.match(src, /UFO\.restore\(data\.ufo\)/, 'load path restores UFO visitor schedule');
assert.match(src, /PROGRESS\.restore\(data\.progress\)/, 'load path restores trained progression state');
assert.match(src, /PLANTS\.restore\(data\.plants\)/, 'load path restores living plant state');
assert.match(progressSrc, /trophies:cleanTrophies\(state\.trophies\)/, 'progress snapshots include seasonal trophy history');
assert.match(progressSrc, /state\.trophies=cleanTrophies\(d\.trophies\)/, 'progress restore keeps seasonal trophy history');
assert.match(src, /player\.energy = \(data\.player && typeof data\.player\.energy==='number'\) \? data\.player\.energy : 0/, 'load path restores stored hero energy');
assert.match(src, /function chunkForTerrainSave\(arr\)/, 'save path strips transient world layers from terrain chunks');
assert.match(src, /function stripTransientTerrainTiles\(arr\)/, 'load path sanitizes transient world layers from saved chunks');
assert.match(src, /encodeRLE\(chunkForTerrainSave\(arr\)\)/, 'full and incremental chunk saves encode sanitized terrain chunks');
assert.match(src, /stripTransientTerrainTiles\(ch\.rle\? decodeRLE\(ch\.data, CHUNK_W\*WORLD_H\): decodeRaw\(ch\.data\)\)/, 'inline modified chunk restore removes transient tiles from terrain');
assert.match(src, /stripTransientTerrainTiles\(ref\.rle===false \? decodeRaw\(data\) : decodeRLE\(data, CHUNK_W\*WORLD_H\)\)/, 'referenced autosave restore removes transient tiles from terrain');
assert.match(src, /updateInventory\(\{noSave:true\}\)/, 'load path refreshes inventory UI without dirtying the save');
assert.match(src, /refreshHotbarDom\(\)/, 'load path refreshes visible hotbar labels');
assert.match(src, /updateHotbarSel\(\)/, 'load path refreshes visible hotbar selection');
assert.match(src, /function updateInventory\(opts\)/, 'inventory refresh accepts options');
assert.match(src, /if\(!\(opts&&opts\.noSave\)\) saveState\(\)/, 'inventory refresh can suppress save scheduling');
assert.match(src, /function recordSaveFailure\(e,manual\)/, 'autosave records and backs off after storage failures');
assert.match(src, /function timedSavePart\(label,fn,perf\)/, 'save path has per-subsystem timing instrumentation');
assert.match(src, /window\.__lastSavePerfParts=parts/, 'save path publishes slowest save subsystems for the debug HUD');
assert.match(src, /saveParts=Array\.isArray\(window\.__lastSavePerfParts\)/, 'debug HUD reports slow save subsystems');
assert.match(src, /buildSaveObject\(\{lightweight:true, chunkRefs:job\.refs, auditChunkIds:\[\], perf\}\)/, 'incremental autosave measures lightweight metadata snapshots');
assert.match(src, /job\.encodeMs \+=/, 'incremental autosave tracks chunk encoding time');
assert.match(src, /job\.chunkWriteMs \+=/, 'incremental autosave tracks chunk storage write time');
assert.match(src, /autosaveChunkKey\(cx,job\.id\)/, 'autosave writes unique per-job chunk blobs');
assert.match(src, /cleanupAutosaveChunks\(new Set\(\),job\.refs\)/, 'failed autosave batches clean uncommitted blobs');
assert.match(src, /id:'coal_torches'/, 'crafting exposes a coal-assisted torch recipe');
assert.match(src, /cost:\{wood:1,\s*coal:1\}/, 'coal torch recipe consumes wood and coal');
assert.match(src, /inv\.torch\+=8/, 'coal torch recipe yields the larger torch batch');
assert.match(src, /keyMap=\{cape:'capes', eyes:'eyes', outfit:'outfits', weapon:'weapons', charm:'charms'\}/, 'crafted gear routes to the correct inventory collection by kind');
assert.match(src, /id:'spring_antler_charm'/, 'crafting exposes a spring trophy recipe');
assert.match(src, /cost:\{springAntler:1,\s*leaf:6,\s*wood:2\}/, 'spring trophy recipe consumes the stag antler');
assert.match(src, /id:'summer_horn_charm'/, 'crafting exposes a summer trophy recipe');
assert.match(src, /cost:\{summerHorn:1,\s*grass:8,\s*copper:1\}/, 'summer trophy recipe consumes the bison horn');
assert.match(src, /id:'autumn_heartwood_bow'/, 'crafting exposes an autumn trophy weapon recipe');
assert.match(src, /cost:\{autumnHeartwood:1,\s*wood:4,\s*leaf:4,\s*copperWire:1\}/, 'autumn trophy recipe consumes heartwood and cable');
assert.match(src, /id:'winter_fur_cape'/, 'crafting exposes a winter trophy cape recipe');
assert.match(src, /cost:\{winterFur:1,\s*snow:8,\s*leaf:2\}/, 'winter trophy recipe consumes winter fur');
assert.match(src, /id:'copper_wire'/, 'crafting exposes copper power cable');
assert.match(src, /id:'teleporter'/, 'crafting exposes teleporters');

const sameSeedRegen = src.match(/window\.regenWorldSameSeed = function\(\)\{ try\{([\s\S]*?)window\.addEventListener\('mm-regen-same-seed'/)?.[1] || '';
assert.match(sameSeedRegen, /player\.xp=0/, 'same-seed regeneration resets hero XP');
assert.match(sameSeedRegen, /PROGRESS && PROGRESS\.reset/, 'same-seed regeneration resets progression milestones and trophy history');
assert.match(sameSeedRegen, /respawnPoint=null/, 'same-seed regeneration clears stale respawn points');
assert.match(sameSeedRegen, /grave=null/, 'same-seed regeneration clears stale graves');
assert.match(sameSeedRegen, /if\(godMode\)/, 'same-seed regeneration preserves debug god-mode resource stacks after reset');

console.log('save-schema-sim: all assertions passed');
