// Save-schema regression: resources and hotbar state must survive save/load.
// This is a light static guard because main.js is browser/DOM-bound.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const src = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const indexSrc = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const progressSrc = await readFile(new URL('../src/engine/progress.js', import.meta.url), 'utf8');
const inventorySrc = await readFile(new URL('../src/inventory.js', import.meta.url), 'utf8');
const inventoryUiSrc = await readFile(new URL('../src/inventory_ui.js', import.meta.url), 'utf8');

assert.match(src, /function snapshotInventory\(\)/, 'save code defines an inventory snapshot helper');
assert.match(indexSrc, /id="immunityBtn"/, 'debug HUD exposes an immunity toggle button');
assert.match(src, /let godMode=false, immunityMode=false/, 'main tracks god mode and immunity independently');
assert.match(src, /function toggleImmunity\(\)/, 'main exposes an immunity toggle');
assert.match(src, /if\(immunityMode\)\{ player\.hp=player\.maxHp; return false; \}/, 'damageHero ignores damage while immunity is enabled');
assert.match(src, /if\(immunityMode\)\{ player\.hp=player\.maxHp; return; \}/, 'heroDied refuses death while immunity is enabled');
assert.match(src, /immunityBtn.*addEventListener\('click',toggleImmunity\)/, 'immunity button is wired to the toggle');
assert.match(src, /k==='i'&&!keysOnce\.has\('i'\)/, 'I hotkey toggles immunity');
assert.match(src, /function restoreInventory\(src\)/, 'load code defines an inventory restore helper');
assert.match(src, /function snapshotHotbar\(\)/, 'save code defines a hotbar snapshot helper');
assert.match(src, /function restoreHotbar\(src\)/, 'load code defines a hotbar restore helper');
assert.match(src, /function snapshotEquipment\(\)/, 'save code defines an equipment snapshot helper');
assert.match(src, /function restoreEquipment\(src\)/, 'load code defines an equipment restore helper');
assert.match(src, /infrastructure:\s*timedSavePart\('infrastructure',[^\n]*WORLD && WORLD\.snapshotInfrastructure/, 'save payload includes pipe and cable overlays');
assert.match(src, /background:\s*timedSavePart\('background',[^\n]*BACKGROUND && BACKGROUND\.snapshot/, 'save payload includes day-night background state');
assert.match(src, /constructionBackground:\s*timedSavePart\('constructionBackground',[^\n]*WORLD && WORLD\.snapshotConstructionBackground/, 'save payload includes background construction support tiles');
assert.match(src, /gases:\s*timedSavePart\('gases',[^\n]*GASES && GASES\.snapshot/, 'save payload includes active gas state');
assert.match(src, /fire:\s*timedSavePart\('fire',[^\n]*FIRE && FIRE\.snapshot/, 'save payload includes active burning fire state');
assert.match(src, /wind:\s*timedSavePart\('wind',[^\n]*WIND && WIND\.snapshot/, 'save payload includes weather wind state');
assert.match(src, /seasons:\s*timedSavePart\('seasons',[^\n]*SEASONS && SEASONS\.snapshot/, 'save payload includes season clock state');
assert.match(src, /clouds:\s*timedSavePart\('clouds',[^\n]*CLOUDS && CLOUDS\.snapshot/, 'save payload includes cloud and storm weather state');
assert.match(src, /dynamo:\s*timedSavePart\('dynamo',[^\n]*DYNAMO && DYNAMO\.snapshot/, 'save payload includes dynamo machine state');
assert.match(src, /solar:\s*timedSavePart\('solar',[^\n]*SOLAR && SOLAR\.snapshot/, 'save payload includes solar panel battery state');
assert.match(src, /teleporters:\s*timedSavePart\('teleporters',[^\n]*TELEPORTERS && TELEPORTERS\.snapshot/, 'save payload includes teleporter machine state');
assert.match(src, /pumps:\s*timedSavePart\('pumps',[^\n]*PUMPS && PUMPS\.snapshot/, 'save payload includes water pump machine state');
assert.match(src, /turrets:\s*timedSavePart\('turrets',[^\n]*TURRETS && TURRETS\.snapshot/, 'save payload includes turret battery state');
assert.match(src, /springPlatforms:\s*timedSavePart\('springPlatforms',[^\n]*SPRING_PLATFORMS && SPRING_PLATFORMS\.snapshot/, 'save payload includes spring platform battery state');
assert.match(src, /vending:\s*timedSavePart\('vending',[^\n]*VENDING && VENDING\.snapshot/, 'save payload includes vending machine stock state');
assert.match(src, /volcano:\s*timedSavePart\('volcano',[^\n]*VOLCANO && VOLCANO\.snapshot/, 'save payload includes volcano story-item and hazard state');
assert.match(src, /guardians:\s*timedSavePart\('guardians',[^\n]*GUARDIANS && GUARDIANS\.snapshot/, 'save payload includes elemental guardian state');
assert.match(src, /undergroundBoss:\s*timedSavePart\('undergroundBoss',[^\n]*UNDERGROUND && UNDERGROUND\.snapshot/, 'save payload includes underground boss state');
assert.match(src, /guardianAftermath:\s*timedSavePart\('guardianAftermath',[^\n]*AFTERMATH && AFTERMATH\.snapshot/, 'save payload includes lingering guardian aftermath state');
assert.match(src, /meteorites:\s*timedSavePart\('meteorites',[^\n]*METEORITES && METEORITES\.snapshot/, 'save payload includes meteorite schedule state');
assert.match(src, /mobs:\s*timedSavePart\('mobs',[^\n]*MOBS && MOBS\.serialize/, 'save payload includes live mob ecology state');
assert.match(src, /generatedNpcs:\s*timedSavePart\('generatedNpcs',[^\n]*GENERATED_NPCS && GENERATED_NPCS\.snapshot/, 'save payload includes generated NPC discovery state');
assert.match(src, /npcs:\s*timedSavePart\('npcs',[^\n]*NPCS && NPCS\.snapshot/, 'save payload includes registered NPC system state');
assert.match(src, /tutorialNpc:\s*timedSavePart\('tutorialNpc',[^\n]*TUTORIAL_NPC && TUTORIAL_NPC\.snapshot/, 'save payload includes tutorial mentor quest state');
assert.match(src, /ufo:\s*timedSavePart\('ufo',[^\n]*UFO && UFO\.snapshot/, 'save payload includes UFO visitor schedule state');
assert.match(src, /progress:\s*timedSavePart\('progress',[^\n]*PROGRESS && PROGRESS\.snapshot/, 'save payload includes trained progression state');
assert.match(src, /plants:\s*timedSavePart\('plants',[^\n]*PLANTS && PLANTS\.snapshot/, 'save payload includes living plant state');
assert.match(src, /inv:\s*timedSavePart\('inventory',[^\n]*snapshotInventory\(\)/, 'save payload includes resource inventory');
assert.match(src, /hotbar:\s*timedSavePart\('hotbar',[^\n]*snapshotHotbar\(\)/, 'save payload includes hotbar state');
assert.match(src, /equipment:\s*timedSavePart\('equipment',[^\n]*snapshotEquipment\(\)/, 'save payload includes equipped gear and outfit');
assert.match(src, /tool:\s*player\.tool/, 'save payload includes the active pickaxe');
assert.match(src, /energy:\+\(player\.energy\|\|0\)\.toFixed\(2\)/, 'save payload includes stored hero energy');
assert.match(src, /restoreInventory\(data\.inv\)/, 'load path restores resource inventory');
assert.match(src, /restoreHotbar\(data\.hotbar/, 'load path restores hotbar state');
assert.match(src, /restoreEquipment\(data\.equipment\)/, 'load path restores equipped gear and outfit');
assert.match(src, /WORLD\.restoreInfrastructure\(data\.infrastructure\)/, 'load path restores pipe and cable overlays after terrain');
assert.match(src, /WORLD\.restoreConstructionBackground\(data\.constructionBackground\)/, 'load path restores background construction support tiles after terrain');
assert.match(src, /BACKGROUND\.restore\(data\.background\)/, 'load path restores day-night background state');
assert.match(src, /GASES\.restore\(data\.gases,getTile,setTile\)/, 'load path restores active gas state through transient world writes');
assert.match(src, /GASES\.auditChunks\(restoredChunks,getTile\)/, 'load path re-audits saved gas tiles from chunks');
assert.match(src, /FIRE\.restore\(data\.fire,getTile\)/, 'load path restores active burning fire after terrain');
assert.match(src, /WIND\.restore\(data\.wind\)/, 'load path restores weather wind state');
assert.match(src, /SEASONS\.restore\(data\.seasons\)/, 'load path restores season clock state');
assert.match(src, /CLOUDS\.restore\(data\.clouds\)/, 'load path restores cloud and storm weather state');
assert.match(src, /DYNAMO\.restore\(data\.dynamo,getTile\)/, 'load path restores dynamo machine state after terrain');
assert.match(src, /SOLAR\.restore\(data\.solar,getTile\)/, 'load path restores solar panel battery state after terrain');
assert.match(src, /TELEPORTERS\.restore\(data\.teleporters,getTile\)/, 'load path restores teleporter batteries after terrain');
assert.match(src, /PUMPS\.restore\(data\.pumps,getTile\)/, 'load path restores water pump batteries after terrain');
assert.match(src, /TURRETS\.restore\(data\.turrets,getTile\)/, 'load path restores turret batteries after terrain');
assert.match(src, /SPRING_PLATFORMS\.restore\(data\.springPlatforms,getTile\)/, 'load path restores spring platform batteries after terrain');
assert.match(src, /VENDING\.restore\(data\.vending,getTile\)/, 'load path restores vending machine stock after terrain');
assert.match(src, /VOLCANO\.restore\(data\.volcano,getTile\)/, 'load path restores volcano story-item timers after terrain');
assert.match(src, /GUARDIANS\.restore\(data\.guardians\)/, 'load path restores guardian progression runtime state');
assert.match(src, /UNDERGROUND\.restore\(data\.undergroundBoss\)/, 'load path restores underground boss runtime state');
assert.match(src, /AFTERMATH\.restore\(data\.guardianAftermath\)/, 'load path restores lingering guardian aftermath runtime state');
assert.match(src, /METEORITES\.restore\(data\.meteorites\)/, 'load path restores meteorite schedule state');
assert.match(src, /MOBS\.deserialize\(data\.mobs\)/, 'load path restores live mob ecology after terrain');
assert.match(src, /GENERATED_NPCS\.restore\(data\.generatedNpcs\)/, 'load path restores generated NPC discovery metadata before the NPC registry');
assert.match(src, /NPCS\.restore\(data\.npcs\)/, 'load path restores the registered NPC system state');
assert.match(src, /TUTORIAL_NPC\.restore\(data\.tutorialNpc\)/, 'load path restores tutorial mentor quest state');
assert.match(src, /TUTORIAL_NPC\.placeNearWorldStart\(getTile,WORLDGEN\)/, 'old saves place the tutorial mentor near the world start');
assert.match(src, /const tutorialNpcCtx = \{damageHero:window\.damageHero, onInventoryChange:updateInventory, onChange:saveState, worldGen:WORLDGEN, gameDayFloat:\(\)=>\{[^}]+SEASONS && SEASONS\.metrics[^}]+\}\};\s*if\(NPCS && NPCS\.setContext\) NPCS\.setContext\(tutorialNpcCtx\);/, 'main registers one shared NPC context for quest saves, HUD refreshes, hero damage, and in-game day scheduling');
assert.match(src, /NPCS\.handleKey\(e\.key,player,tutorialNpcCtx\)/, 'NPC reward-choice keys are handled before weapon shortcuts through the shared quest context');
assert.match(src, /function selectWeaponKey\(key\)\{\s*if\(NPCS && NPCS\.handleKey && NPCS\.handleKey\(key,player,tutorialNpcCtx\)\) return;/, 'on-screen weapon buttons can also answer NPC reward choices through the shared quest context');
assert.match(src, /NPCS\.attackAt\(tx,ty,atkBonus,tutorialNpcCtx\)/, 'direct melee attacks pass the shared NPC quest context');
assert.match(src, /GENERATED_NPCS\.update\(dt, player, getTile, setTile, tutorialNpcCtx\)/, 'generated NPC discovery runs before registered NPC simulation');
assert.match(src, /GENERATED_NPCS\.draw\(ctx,TILE,worldFxVisible,getTile,WORLDGEN\)/, 'generated NPC homes are drawn from the manager before NPC actors');
assert.match(src, /NPCS\.update\(dt, player, getTile, setTile, tutorialNpcCtx\)/, 'NPC update uses the same shared quest context as damage and input paths');
assert.match(src, /UFO\.restore\(data\.ufo\)/, 'load path restores UFO visitor schedule');
assert.match(src, /PROGRESS\.restore\(data\.progress\)/, 'load path restores trained progression state');
assert.match(src, /PLANTS\.restore\(data\.plants\)/, 'load path restores living plant state');
assert.match(src, /import \{ guardianLairs as GUARDIANS \} from '\.\/engine\/guardian_lairs\.js';/, 'main imports the elemental guardian engine');
assert.match(src, /import \{ undergroundBoss as UNDERGROUND \} from '\.\/engine\/underground_boss\.js';/, 'main imports the underground boss engine');
assert.match(src, /import \{ guardianAftermath as AFTERMATH \} from '\.\/engine\/guardian_aftermath\.js';/, 'main imports the lingering guardian aftermath engine');
assert.match(src, /GUARDIANS && GUARDIANS\.update/, 'main update loop advances elemental guardians');
assert.match(src, /UNDERGROUND && UNDERGROUND\.update/, 'main update loop advances the underground boss');
assert.match(src, /AFTERMATH && AFTERMATH\.update/, 'main update loop advances guardian aftermath consequences');
assert.match(src, /GUARDIANS && GUARDIANS\.draw/, 'main draw loop renders elemental guardians');
assert.match(src, /UNDERGROUND && UNDERGROUND\.draw/, 'main draw loop renders the underground boss');
assert.match(src, /AFTERMATH && AFTERMATH\.draw/, 'main draw loop renders guardian aftermath consequences');
assert.match(src, /GUARDIANS && GUARDIANS\.attackAt/, 'melee attacks can hit elemental guardians');
assert.match(src, /UNDERGROUND && UNDERGROUND\.attackAt/, 'melee attacks can hit the underground boss');
assert.match(progressSrc, /trophies:cleanTrophies\(state\.trophies\)/, 'progress snapshots include seasonal trophy history');
assert.match(progressSrc, /state\.trophies=cleanTrophies\(d\.trophies\)/, 'progress restore keeps seasonal trophy history');
assert.match(progressSrc, /guardians:cleanGuardians\(state\.guardians\)/, 'progress snapshots include guardian heart history');
assert.match(progressSrc, /state\.guardians=cleanGuardians\(d\.guardians\)/, 'progress restore keeps guardian heart history');
assert.match(progressSrc, /GUARDIAN_KEYS=\[[^\]]*'earth'[^\]]*\]/, 'progress guardian heart history includes earth');
assert.match(progressSrc, /function markGuardianHeart\(kind\)/, 'progress exposes one-time guardian heart marking');
assert.match(inventorySrc, /key:'heartFire'/, 'inventory resources include the Heart of Fire');
assert.match(inventorySrc, /key:'heartIce'/, 'inventory resources include the Heart of Ice');
assert.match(inventorySrc, /key:'heartEarth'/, 'inventory resources include the Heart of Earth');
assert.match(src, /player\.energy = \(data\.player && typeof data\.player\.energy==='number'\) \? data\.player\.energy : 0/, 'load path restores stored hero energy');
assert.match(src, /function chunkForTerrainSave\(arr\)/, 'save path strips transient world layers from terrain chunks');
assert.match(src, /function stripTransientTerrainTiles\(arr\)/, 'load path sanitizes transient world layers from saved chunks');
assert.match(src, /function migrateLegacyInfrastructureTerrain\(cx,arr\)/, 'load path migrates legacy pipe and cable terrain into overlays');
assert.match(src, /function restoreTerrainChunk\(cx,arr\)/, 'chunk restore uses one shared terrain cleanup helper');
assert.match(src, /stripTransientTerrainTiles\(arr\);\s*migrateLegacyInfrastructureTerrain\(cx,arr\);/, 'terrain restore strips transient tiles before migrating infrastructure overlays');
assert.match(src, /timedSavePart\('falling\.audit',[^\n]*FALLING\.auditChunks\(saveChunkIds,\{force:true,immediate:true\}\)/, 'full save audits modified chunks through falling physics before settling terrain');
assert.match(src, /timedSavePart\('falling\.settle',[^\n]*FALLING\.settleAll\(\)/, 'full save settles queued falling physics before chunk serialization');
assert.match(src, /FALLING\.auditChunks\(\[cx\],\{force:true,immediate:true\}\)/, 'incremental autosave audits each chunk through falling physics before writing its blob');
assert.match(src, /encodeRLE\(chunkForTerrainSave\(arr\)\)/, 'full and incremental chunk saves encode sanitized terrain chunks');
assert.match(src, /restoreTerrainChunk\(ch\.cx,arr\)/, 'inline modified chunk restore removes transient and legacy overlay tiles from terrain');
assert.match(src, /restoreTerrainChunk\(ref\.cx,arr\)/, 'referenced autosave restore removes transient and legacy overlay tiles from terrain');
assert.match(src, /updateInventory\(\{noSave:true\}\)/, 'load path refreshes inventory UI without dirtying the save');
assert.match(src, /refreshHotbarDom\(\)/, 'load path refreshes visible hotbar labels');
assert.match(src, /updateHotbarSel\(\)/, 'load path refreshes visible hotbar selection');
assert.match(src, /function updateInventory\(opts\)/, 'inventory refresh accepts options');
assert.match(src, /if\(!\(opts&&opts\.noSave\)\) saveState\(\)/, 'inventory refresh can suppress save scheduling');
assert.match(src, /function recordSaveFailure\(e,manual\)/, 'autosave records and backs off after storage failures');
assert.match(src, /function timedSavePart\(label,fn,perf\)/, 'save path has per-subsystem timing instrumentation');
assert.match(src, /window\.__lastSavePerfParts=parts/, 'save path publishes slowest save subsystems for the debug HUD');
assert.match(src, /saveParts=Array\.isArray\(window\.__lastSavePerfParts\)/, 'debug HUD reports slow save subsystems');
assert.match(src, /buildSaveObject\(\{lightweight:true, chunkRefs:job\.refs, auditChunkIds:\[\], perf\}\)/, 'incremental autosave measures lightweight metadata snapshots');
assert.match(src, /job\.encodeMs \+=/, 'incremental autosave tracks chunk encoding time');
assert.match(src, /job\.chunkWriteMs \+=/, 'incremental autosave tracks chunk storage write time');
assert.match(src, /autosaveChunkKey\(cx,job\.id\)/, 'autosave writes unique per-job chunk blobs');
assert.match(src, /cleanupAutosaveChunks\(new Set\(\),job\.refs\)/, 'failed autosave batches clean uncommitted blobs');
assert.match(src, /id:'coal_torches'/, 'crafting exposes a coal-assisted torch recipe');
assert.match(src, /cost:\{wood:1,\s*coal:1\}/, 'coal torch recipe consumes wood and coal');
assert.match(src, /inv\.torch\+=8/, 'coal torch recipe yields the larger torch batch');
assert.match(src, /tools=\{basic:1,stone:2,meteor:3\.3,diamond:4\}/, 'tool speed table includes a meteoric iron pickaxe tier');
assert.match(src, /function isUnmineableTile\(t\)\{ return !!\(INFO\[t\] && INFO\[t\]\.unmineable\); \}/, 'mining centralizes unmineable tile checks');
assert.match(src, /if\(isUnmineableTile\(t\)\)\{ if\(!quiet\) msg\(unmineableReason\(t\)\); return false; \}/, 'cursor mining rejects unmineable tiles before timers start');
assert.match(src, /if\(t===T\.AIR \|\| isUnmineableTile\(t\)\)/, 'instant break cannot bypass unmineable tiles');
assert.match(src, /if\(info\.unmineable\) return false;/, 'breakMinedTile refuses unmineable terrain at the final write point');
assert.match(src, /tools:\{stone:!!inv\.tools\.stone,\s*meteor:!!inv\.tools\.meteor,\s*diamond:!!inv\.tools\.diamond\}/, 'inventory snapshot persists the meteoric pickaxe');
assert.match(src, /inv\.tools\.stone=false;\s*inv\.tools\.meteor=false;\s*inv\.tools\.diamond=false/, 'inventory restore clears the meteoric pickaxe before loading');
assert.match(src, /inv\.tools\.meteor=!!src\.tools\.meteor/, 'inventory restore loads the meteoric pickaxe flag');
assert.match(src, /PICK_ORDER=\['basic','stone','meteor','diamond'\]/, 'pickaxe cycling includes the meteoric pickaxe between stone and diamond');
assert.match(inventoryUiSrc, /inv\.tools && inv\.tools\.meteor\?\['meteorytowy'\]:\[\]/, 'resource panel lists the meteoric pickaxe when owned');
assert.match(src, /id:'pick_meteoric_iron'/, 'crafting exposes a meteoric iron pickaxe recipe');
assert.match(src, /cost:\{meteoricIron:5,\s*coal:2\}/, 'meteoric pickaxe recipe consumes meteor material');
assert.match(src, /id:'arrows_wood_small'/, 'crafting exposes a small wooden arrow recipe');
assert.match(src, /cost:\{wood:1\}/, 'small wooden arrow recipe consumes one wood block');
assert.match(src, /inv\.arrowWood\+=10/, 'small wooden arrow recipe yields ten arrows');
assert.match(src, /id:'arrows_wood_bulk'/, 'crafting exposes bulk wooden arrows');
assert.match(src, /id:'arrows_stone_bulk'/, 'crafting exposes stone-tipped arrows');
assert.match(src, /id:'arrows_obsidian_bulk'/, 'crafting exposes obsidian-tipped arrows');
assert.match(src, /id:'arrows_diamond_bulk'/, 'crafting exposes diamond-tipped arrows');
assert.match(src, /id:'arrows_iridium_bulk'/, 'crafting exposes iridium-tipped arrows');
assert.match(src, /cost:\{wood:10,\s*iridium:1\}/, 'iridium arrow recipe consumes wood plus meteorite iridium');
assert.match(src, /inv\.arrowIridium\+=100/, 'bulk iridium arrow recipe yields one hundred arrows');
assert.match(src, /keyMap=\{cape:'capes', eyes:'eyes', outfit:'outfits', weapon:'weapons', charm:'charms'\}/, 'crafted gear routes to the correct inventory collection by kind');
assert.match(src, /id:'spring_antler_charm'/, 'crafting exposes a spring trophy recipe');
assert.match(src, /cost:\{springAntler:1,\s*leaf:6,\s*wood:2\}/, 'spring trophy recipe consumes the stag antler');
assert.match(src, /id:'summer_horn_charm'/, 'crafting exposes a summer trophy recipe');
assert.match(src, /cost:\{summerHorn:1,\s*grass:8,\s*copper:1\}/, 'summer trophy recipe consumes the bison horn');
assert.match(src, /id:'autumn_heartwood_bow'/, 'crafting exposes an autumn trophy weapon recipe');
assert.match(src, /cost:\{autumnHeartwood:1,\s*wood:4,\s*leaf:4,\s*copperWire:1\}/, 'autumn trophy recipe consumes heartwood and cable');
assert.match(src, /id:'winter_fur_cape'/, 'crafting exposes a winter trophy cape recipe');
assert.match(src, /cost:\{winterFur:1,\s*snow:8,\s*leaf:2\}/, 'winter trophy recipe consumes winter fur');
assert.match(src, /id:'copper_wire'/, 'crafting exposes copper power cable');
assert.match(src, /id:'water_pipe'/, 'crafting exposes water pipes');
assert.match(src, /id:'water_pump'/, 'crafting exposes water pumps');
assert.match(src, /id:'glass_from_sand'/, 'crafting exposes sand-to-glass processing');
assert.match(src, /cost:\{sand:2,\s*coal:1\}/, 'glass processing consumes sand and coal');
assert.match(src, /id:'bricks_from_clay'/, 'crafting exposes clay-to-brick processing');
assert.match(src, /cost:\{clay:3,\s*coal:1\}/, 'brick processing consumes clay and coal');
assert.match(src, /inv\.brick\+=3/, 'brick processing yields brick blocks');
assert.match(src, /id:'steel_from_meteoric_iron'/, 'crafting exposes meteoric iron steelmaking');
assert.match(src, /cost:\{meteoricIron:2,\s*coal:1\}/, 'steel processing consumes meteoric iron and coal');
assert.match(src, /id:'transistor_basic'/, 'crafting exposes a basic electronics recipe');
assert.match(src, /id:'vending_machine'/, 'crafting exposes placeable vending machines');
assert.match(src, /id:'teleporter'/, 'crafting exposes teleporters');
assert.match(src, /id:'turret'/, 'crafting exposes basic turrets');
assert.match(src, /id:'fire_turret'/, 'crafting exposes fire turrets');
assert.match(src, /id:'water_turret'/, 'crafting exposes water turrets');
assert.match(src, /id:'spring_platform'/, 'crafting exposes spring platforms');
assert.match(src, /cost:\{steel:2,\s*copperWire:2,\s*transistor:1\}/, 'spring platform recipe consumes steel and electronics components');
assert.match(src, /const CRAFT_GROUPS=\[/, 'crafting has recipe-book groups instead of one flat list');
assert.match(src, /const CRAFT_GROUP_ORDER=\{\}; CRAFT_GROUPS\.forEach\(\(g,i\)=>\{ CRAFT_GROUP_ORDER\[g\.id\]=i; \}\)/, 'crafting preserves recipe-book group order for the all-recipes view');
assert.match(src, /const CRAFT_RECIPE_META=\{/, 'crafting recipes carry UI metadata separately from effects');
assert.match(src, /function recipeMissing\(r\)/, 'crafting can report missing ingredients per recipe');
assert.match(src, /function recipeMaxCrafts\(r\)/, 'crafting computes craftable batch capacity from inventory');
assert.match(src, /function filteredCraftRecipes\(\)/, 'crafting filters recipes by group and search text');
assert.match(src, /function renderCraftPanel\(\)/, 'crafting renders through the recipe-book panel');
assert.match(src, /search\.addEventListener\('input',\(\)=>\{ craftQuery=search\.value\|\|''; renderCraftPanel\(\); \}\)/, 'crafting search updates the visible recipe list');

const sameSeedRegen = src.match(/window\.regenWorldSameSeed = function\(\)\{ try\{([\s\S]*?)window\.addEventListener\('mm-regen-same-seed'/)?.[1] || '';
assert.match(sameSeedRegen, /player\.xp=0/, 'same-seed regeneration resets hero XP');
assert.match(sameSeedRegen, /PROGRESS && PROGRESS\.reset/, 'same-seed regeneration resets progression milestones and trophy history');
assert.match(sameSeedRegen, /respawnPoint=null/, 'same-seed regeneration clears stale respawn points');
assert.match(sameSeedRegen, /grave=null/, 'same-seed regeneration clears stale graves');
assert.match(sameSeedRegen, /if\(godMode\)/, 'same-seed regeneration preserves debug god-mode resource stacks after reset');

console.log('save-schema-sim: all assertions passed');
