import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createTemporalEchoController } from '../src/engine/temporal_echo.js';

const echo=createTemporalEchoController({durationSeconds:60,cooldownSeconds:180});
assert.equal(echo.state().phase,'idle');
assert.equal(echo.arm({death:{x:4,y:9}}),true);
assert.equal(echo.arm({}),false,'nested checkpoints are refused');
assert.equal(echo.update(30),null,'timer does not run during death travel');
assert.equal(echo.state().remaining,60);
assert.equal(echo.beginRace(),true);
assert.equal(echo.update(59.75),null);
assert.ok(echo.state().remaining>0 && echo.state().remaining<0.26);
assert.deepEqual(echo.update(0.25),{type:'expired'});
assert.equal(echo.collapse('expired'),true);
assert.equal(echo.arm({death:{x:-2,y:17}}),true);
assert.equal(echo.beginRace(),true);
assert.equal(echo.beginRewind(),true);
assert.equal(echo.finishRewind(),true);
assert.equal(echo.state().cooldown,180);
echo.update(179.9);
assert.equal(echo.arm({}),false);
echo.update(0.1);
assert.equal(echo.arm({}),true);

const main=readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const world=readFileSync(new URL('../src/engine/world.js',import.meta.url),'utf8');
const mobs=readFileSync(new URL('../src/engine/mobs.js',import.meta.url),'utf8');
const trees=readFileSync(new URL('../src/engine/trees.js',import.meta.url),'utf8');
const falling=readFileSync(new URL('../src/engine/falling.js',import.meta.url),'utf8');
const audio=readFileSync(new URL('../src/engine/audio.js',import.meta.url),'utf8');
assert.match(main,/captureTemporalEcho\(cause\)[\s\S]*buildSaveObject\(\{lightweight:true[\s\S]*TEMPORAL_ECHO\.arm/);
assert.match(main,/const incomplete=Object\.entries\(payload\.data[\s\S]*complete===false/, 'lossy subsystem snapshots refuse to arm an inaccurate rewind');
assert.match(main,/window\.heroDied=function\(cause\)[\s\S]*captureTemporalEcho\(cause\)[\s\S]*HERO_STATUS\.clearAll/);
assert.match(main,/temporalEchoEligible\(cause\)[\s\S]*MM\.challenge\.isIronman/, 'ironman runs cannot rewind their one permitted death');
assert.match(main,/rememberTemporalPending\(payload\)[\s\S]*TEMPORAL_PENDING_KEY/, 'an unresolved branch leaves crash-recovery evidence');
assert.match(main,/pending && pending\.v===1[\s\S]*temporalCooldownUntil=Math\.max/, 'crash recovery cannot miss a non-default world before its seed loads');
assert.match(main,/persistTemporalCooldown\(\)[\s\S]*TEMPORAL_COOLDOWN_MS/, 'successful rewind cooldown survives reload');
assert.match(main,/resetWorldTransitionRuntime\(\)[\s\S]*clearTemporalPending\(\)/, 'intentional world transitions clear the crash marker');
assert.match(main,/finishDeathTravelRespawn\(\)[\s\S]*TEMPORAL_ECHO\.beginRace/);
assert.match(main,/tryOpenGraveAt\(tx,ty\)[\s\S]*beginTemporalRewind/);
assert.match(main,/function breakMinedTile\(\)[\s\S]*tId===T\.GRAVE\) return tryOpenGraveAt/, 'finishing a grave mining action resolves the grave instead of deleting its tile');
assert.match(main,/function repairTemporalGrave\(\)[\s\S]*setTile\(grave\.x,grave\.y,T\.GRAVE\)[\s\S]*collapseTemporalEcho\('grave-lost'/, 'external grave destruction self-heals or fails closed');
assert.match(main,/function updateTemporalEcho\(dt\)[\s\S]*state\.phase==='racing'[\s\S]*repairTemporalGrave\(\)/, 'the racing loop enforces the grave objective invariant');
assert.match(main,/findGroundedGraveCell\(cx,cy,[\s\S]*isSupport:isObjectFootingTile/, 'death markers require physical footing instead of freezing in open air');
assert.match(main,/t===T\.GRAVE && !activeTemporalSpiritAt\(wx,y\)[\s\S]*drawGraveTile/, 'the temporal interaction anchor never bakes a floating stone marker');
assert.match(main,/function drawTemporalEchoSpirit\([\s\S]*Clock halo[\s\S]*Temporal motes/, 'the Echo target is a distinct animated spirit');
assert.match(main,/function refreshGraveMarkerVisual\([\s\S]*entry\.version=-1[\s\S]*chunkRenderDirty\.delete/, 'a surviving resource grave is rebaked when the spirit expires');
assert.match(main,/kind:'spirit'/, 'the QA contract identifies the new target presentation');
assert.match(main,/restoreTemporalEchoPayload\(payload\)[\s\S]*restoreTemporalCheckpoint\(\)[\s\S]*player\.hp=player\.maxHp[\s\S]*hpInvul/);
assert.match(main,/restoreTemporalEchoPayload\(payload\)[\s\S]*DISCOVERY\.restore\(payload\.discovery\)/, 'branch-only discoveries are rolled back with their XP');
assert.match(main,/restoreTemporalEchoPayload\(payload\)[\s\S]*applyProgressHp\(\)[\s\S]*applyHeroEnergyCapacity\(\)/, 'derived hero capacities are recomputed from restored progression and gear');
assert.match(main,/getTile\(gx,gy\)!==T\.GRAVE[\s\S]*zasoby zostały zwrócone/, 'failed grave placement refunds resources instead of creating an impossible objective');
assert.match(main,/function saveState\(\)[\s\S]*temporalEchoActive\(\)\) return/);
assert.match(main,/function drawTemporalEchoOverlay\(ts\)[\s\S]*globalCompositeOperation='screen'/);
assert.match(main,/function drawTemporalEchoOverlay\(ts\)[\s\S]*createRadialGradient/);
assert.match(main,/function drawTemporalEchoOverlay\(ts\)[\s\S]*COFANIE/);
assert.match(world,/TEMPORAL_SECTION_CAP=2048/);
assert.match(world,/function rememberTemporalSection[\s\S]*arr\.slice\(\)/, 'terrain uses section-level copy-on-write');
assert.match(world,/function invalidateTemporalJournal[\s\S]*temporalJournal\.invalid=true/);
assert.match(world,/function restoreTemporalCheckpoint\(\)[\s\S]*journal\.sections\.values\(\)/);
assert.match(world,/journal\.chunkMeta\.values\(\)[\s\S]*modifiedChunks/, 'discarded branches do not permanently pin generated chunks');
assert.match(mobs,/function temporalSnapshot\(\)[\s\S]*projectiles:mobProjectiles[\s\S]*lasers:mobLasers/);
assert.match(mobs,/function temporalRestore\(src\)[\s\S]*mobProjectiles\.length=0[\s\S]*mobLasers\.length=0/, 'fatal-moment hostile combat transients are restored');
assert.match(trees,/complete=fallenTreeTiles\.size[\s\S]*rotating/, 'falling trees and oversized registries are represented explicitly');
assert.match(falling,/const complete=active\.length[\s\S]*unstable\.size<=6000/, 'falling-terrain truncation fails closed for temporal capture');
assert.match(audio,/temporalArm:[\s\S]*temporalRewind:[\s\S]*temporalReturn:/);
console.log('temporal-echo-sim: all assertions passed');
